# Generated by Django 2.1.15 on 2020-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('idAbono', models.BigAutoField(db_column='idAbono', primary_key=True, serialize=False)),
                ('monto', models.FloatField(blank=True, db_column='monto')),
            ],
            options={
                'db_table': 'Abono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apartar',
            fields=[
                ('idApartar', models.BigAutoField(db_column='idApartar', primary_key=True, serialize=False)),
                ('diaApartar', models.IntegerField(blank=True, db_column='diaApartar')),
                ('mesApartar', models.IntegerField(blank=True, db_column='mesApartar')),
                ('anioApartar', models.IntegerField(blank=True, db_column='anioApartar')),
            ],
            options={
                'db_table': 'Apartar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idAr', models.BigAutoField(db_column='idAr', primary_key=True, serialize=False)),
                ('nameAr', models.CharField(blank=True, db_column='nameAr', max_length=30)),
                ('talla', models.CharField(blank=True, db_column='talla', max_length=1)),
                ('cantidad', models.IntegerField(blank=True, db_column='cantidad')),
                ('precio', models.FloatField(blank=True, db_column='precio')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcat', models.BigAutoField(db_column='idcat', primary_key=True, serialize=False)),
                ('namecat', models.CharField(blank=True, db_column='namecat', max_length=30)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.BigAutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nameCl', models.CharField(blank=True, db_column='nameCl', max_length=30)),
                ('apellidoP', models.CharField(blank=True, db_column='apellidoP', max_length=30)),
                ('apellidoM', models.CharField(blank=True, db_column='apellidoM', max_length=30)),
                ('calle', models.CharField(blank=True, db_column='calle', max_length=30)),
                ('numero', models.IntegerField(blank=True, db_column='numero')),
                ('colonia', models.CharField(blank=True, db_column='colonia', max_length=30)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=10)),
                ('puntos', models.IntegerField(blank=True, db_column='puntos')),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadA', models.IntegerField(blank=True, db_column='cantidadA')),
            ],
            options={
                'db_table': 'DetalleVenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idTipo', models.BigAutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nameTipo', models.CharField(blank=True, db_column='nameTipo', max_length=30)),
                ('puntosT', models.IntegerField(blank=True, db_column='puntosT')),
            ],
            options={
                'db_table': 'TipoCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.BigAutoField(db_column='idVenta', primary_key=True, serialize=False)),
                ('total', models.FloatField(blank=True, db_column='total')),
            ],
            options={
                'db_table': 'Venta',
                'managed': False,
            },
        ),
    ]
